version: '3.5'
services:
    php:
        image: uusa35/laravel-k8:latest
        restart: always
        ports:
            - 8000:80
        environment:
            - APP_KEY="base64:rai7yX3Q1mMx2QDQbNmk7PPQwelfjztWy8rEmiKZOLM="
            - APP_ENV=local
            - APP_DEBUG=true
            - DB_PORT=3306
            - DB_HOST=mysql
            - DB_DATABASE
            - DB_USERNAME
            - DB_PASSWORD
    mysql:
        image: mysql:8.0.31
        restart: always
        environment:
            - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
            - MYSQL_DATABASE=${DB_DATABASE}
            - MYSQL_USER=${DB_USERNAME}
            - MYSQL_PASSWORD=${DB_PASSWORD}
